services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: defalut
      POSTGRES_PASSWORD: rLBhM4iA5ekC
      POSTGRES_DB: verceldb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
