services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tgifmike
      POSTGRES_PASSWORD: bipke4-xexzAs-caxqed
      POSTGRES_DB: newblog
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
